# Generated by Django 3.2.5 on 2022-08-22 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='nickname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'La longitud debe ser mayor a 1')]),
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Enter the make of the car (e.g. Honda)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'La longitud debe ser mayor a 2')]),
        ),
    ]
